spring:
  application:
    name: Adventure Pos

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME:adventurepos}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
      schema: public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        '[id.new_generator_mappings]': true
        '[connection.provider_disables_autocommit]': true
        '[cache.use_second_level_cache]': false
        '[cache.use_query_cache]': false
        '[hibernate.generate_statistics]': false
        '[format_sql]': false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

